import { BarChart3, TrendingUp, ShieldAlert, Target, Eye } from "lucide-react";

const METHODS = [
  {
    icon: BarChart3,
    title: "Multi-Factor Scoring",
    desc: "Stocks are evaluated across multiple dimensions including fundamentals, valuation, momentum, institutional activity, sector strength, and risk stability.",
  },
  {
    icon: TrendingUp,
    title: "Valuation Models",
    desc: "Intrinsic value is estimated using discounted cash flow projections, relative valuation multiples, and probability-weighted price scenarios.",
  },
  {
    icon: ShieldAlert,
    title: "Risk Framework",
    desc: "The engine evaluates volatility, leverage, macro exposure, and earnings stability to estimate downside risk.",
  },
  {
    icon: Target,
    title: "Scenario Forecasting",
    desc: "Price projections are generated using bull, base, and bear case scenarios with probability weighting.",
  },
  {
    icon: Eye,
    title: "Transparent Output",
    desc: "Every report includes score breakdowns, model agreement indicators, valuation bands, and key drivers behind the recommendation.",
  },
];

const Methodology = () => (
  <div className="border-t border-border bg-background">
    <div className="max-w-4xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
      <p className="font-mono text-[10px] tracking-[4px] uppercase text-muted-foreground mb-2 text-center">
        Framework
      </p>
      <h2 className="font-display text-2xl sm:text-3xl font-bold text-foreground text-center mb-4">
        Methodology & Transparency
      </h2>
      <p className="text-sm text-muted-foreground text-center max-w-2xl mx-auto leading-relaxed mb-10">
        Every analysis generated by the MII Engine is based on structured financial models and transparent scoring frameworks.
        The system evaluates stocks using multiple analytical layers to ensure conclusions are explainable and consistent.
      </p>

      <div className="space-y-0">
        {METHODS.map((m, i) => (
          <div
            key={m.title}
            className={`flex items-start gap-4 py-5 px-1 ${i < METHODS.length - 1 ? 'border-b border-border' : ''}`}
          >
            <div className="w-9 h-9 rounded-md border border-border bg-card flex items-center justify-center shrink-0 mt-0.5">
              <m.icon className="h-4 w-4 text-primary" />
            </div>
            <div>
              <p className="font-mono text-[12px] sm:text-[13px] font-semibold tracking-wide text-foreground mb-1">
                {m.title}
              </p>
              <p className="text-[12px] sm:text-[13px] text-muted-foreground leading-relaxed">
                {m.desc}
              </p>
            </div>
          </div>
        ))}
      </div>
    </div>
  </div>
);

export default Methodology;
